---
version: '3.9'

services:
  fastapi:
    image: {{ cookiecutter.project_slug }}-local
    build:
      context: ./
      dockerfile: ./docker/local/Dockerfile
    ports:
      - "{{ cookiecutter.app_port }}:{{ cookiecutter.app_port }}"
    volumes:
      - ./app:/usr/src/app
      - ./tests:/usr/src/tests
    networks:
      - {{ cookiecutter.project_slug }}-local-network

networks:
  {{ cookiecutter.project_slug }}-local-network:
