---
version: '3.9'

services:
  fastapi:
    image: {{ cookiecutter.project_slug }}-local
    build:
      context: ./
      dockerfile: ./docker/local/Dockerfile
    ports:
      - "{{ cookiecutter.app_port }}:{{ cookiecutter.app_port }}"
    volumes:
      - ./app:/usr/src/app
      - ./tests:/usr/src/tests
    env_file:
      - ./docker/local/.db.env
      - ./docker/local/.env
    networks:
      - {{ cookiecutter.project_slug }}-local-network

  db:
    image: postgres:{{ cookiecutter.postgres_version }}-alpine
    container_name: {{ cookiecutter.project_slug }}-local-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker/local/.db.env
    networks:
      - {{ cookiecutter.project_slug }}-local-network

networks:
  {{ cookiecutter.project_slug }}-local-network:

volumes:
  postgres_data:
