---
version: '3.9'

services:
  fastapi:
    image: {{ cookiecutter.project_slug }}-production
    build:
      context: ./
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - "{{ cookiecutter.app_port }}:{{ cookiecutter.app_port }}"
    env_file:
      - ./docker/prod/.db.env
      - ./docker/prod/.env
