---
version: '3.9'

services:
  fastapi:
    image: {{ cookiecutter.project_slug }}-production
    build:
      context: ./
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - "{{ cookiecutter.app_port }}:{{ cookiecutter.app_port }}"
    volumes:
      - ./app:/usr/src/app
      - ./tests:/usr/src/tests
    networks:
      - {{ cookiecutter.project_slug }}-prod-network

networks:
  {{ cookiecutter.project_slug }}-prod-network:
